export const CHURN_MODEL = "churn_model"
export const RETENTION_MODEL = "retention_model"
export const CONVERSION_MODEL = "conversion_model"
export const FREQUENCY_MODEL = "frequency_model"
export const PREMADE_MODEL = "premade_model"